// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/discover-redesign/BoldSporty.tsx": () => import("../components/mockups/discover-redesign/BoldSporty.tsx"),
  "./components/mockups/discover-redesign/CleanMarketplace.tsx": () => import("../components/mockups/discover-redesign/CleanMarketplace.tsx"),
  "./components/mockups/discover-redesign/DarkPremium.tsx": () => import("../components/mockups/discover-redesign/DarkPremium.tsx")
};
